insert into performers(name) values ('Queen');
insert into albums(title, year) values ('A Night At The Opera', 1975);
insert into gengres(name) values ('Rock');
insert into PerformersGengres(GengreID, performerID) values (1, 1) ON CONFLICT DO NOTHING;
insert into tracks(albumid, title, duration) values (1, 'Death On Two Legs (Dedicated To...)', 223);
insert into tracks(albumid, title, duration) values (1, 'Lazing On A Sunday Afternoon', 67);
insert into tracks(albumid, title, duration) values (1, 'I&ampm In Love With My Car', 186);
insert into tracks(albumid, title, duration) values (1, 'You&ampre My Best Friend', 172);
insert into tracks(albumid, title, duration) values (1, '&amp39', 211);
insert into tracks(albumid, title, duration) values (1, 'Sweet Lady', 244);
insert into tracks(albumid, title, duration) values (1, 'Seaside Rendezvous', 136);
insert into tracks(albumid, title, duration) values (1, 'The Prophet&amps Song', 502);
insert into tracks(albumid, title, duration) values (1, 'Love Of My Life', 220);
insert into tracks(albumid, title, duration) values (1, 'Good Company', 204);
insert into tracks(albumid, title, duration) values (1, 'Bohemian Rhapsody', 355);
insert into tracks(albumid, title, duration) values (1, 'God Save The Queen (Instrumental)', 73);
insert into PerformersAlbums(performerID, albumID) values (1, 1) ON CONFLICT DO NOTHING;

insert into albums(title, year) values ('Queen', 1973);
insert into PerformersGengres(GengreID, performerID) values (1, 1) ON CONFLICT DO NOTHING;
insert into tracks(albumid, title, duration) values (2, 'Keep Yourself Alive', 228);
insert into tracks(albumid, title, duration) values (2, 'Doing All Right', 250);
insert into tracks(albumid, title, duration) values (2, 'Great King Rat', 343);
insert into tracks(albumid, title, duration) values (2, 'My Fairy King', 247);
insert into tracks(albumid, title, duration) values (2, 'Liar', 387);
insert into tracks(albumid, title, duration) values (2, 'The Night Comes Down', 264);
insert into tracks(albumid, title, duration) values (2, 'Modern Times Rock &ampN&amp Roll', 109);
insert into tracks(albumid, title, duration) values (2, 'Son And Daughter', 201);
insert into tracks(albumid, title, duration) values (2, 'Jesus', 225);
insert into tracks(albumid, title, duration) values (2, 'Seven Seas Of Rhye', 67);
insert into PerformersAlbums(performerID, albumID) values (1, 2) ON CONFLICT DO NOTHING;

insert into performers(name) values ('The Beatles');
insert into albums(title, year) values ('A Dolls House', 1968);
insert into gengres(name) values ('Pop');
insert into PerformersGengres(GengreID, performerID) values (2, 2) ON CONFLICT DO NOTHING;
insert into tracks(albumid, title, duration) values (3, 'Mother nature&amps son', 168);
insert into tracks(albumid, title, duration) values (3, 'Long, long, long', 184);
insert into tracks(albumid, title, duration) values (3, 'Julia', 175);
insert into tracks(albumid, title, duration) values (3, 'Wild honey pie', 55);
insert into tracks(albumid, title, duration) values (3, 'Im so tired', 129);
insert into tracks(albumid, title, duration) values (3, 'Rocky Racoon', 214);
insert into tracks(albumid, title, duration) values (3, 'Cry baby cry', 154);
insert into tracks(albumid, title, duration) values (3, 'Savoy truffle', 175);
insert into tracks(albumid, title, duration) values (3, 'I will', 105);
insert into tracks(albumid, title, duration) values (3, 'The continuing story of Bungalow Bill', 195);
insert into tracks(albumid, title, duration) values (3, 'Why dont we do it in the road', 100);
insert into tracks(albumid, title, duration) values (3, 'Happiness is a warm gun', 163);
insert into tracks(albumid, title, duration) values (3, 'Blackbird', 139);
insert into tracks(albumid, title, duration) values (3, 'Honey pie', 162);
insert into tracks(albumid, title, duration) values (3, 'Revolution 1', 256);
insert into tracks(albumid, title, duration) values (3, 'Everybody&amps got something to hide except me and my monkey', 145);
insert into tracks(albumid, title, duration) values (3, 'Glass onion', 138);
insert into tracks(albumid, title, duration) values (3, 'Martha my dear', 148);
insert into tracks(albumid, title, duration) values (3, 'Piggies', 124);
insert into tracks(albumid, title, duration) values (3, 'While my guitar gently weeps', 285);
insert into tracks(albumid, title, duration) values (3, 'Ob-la-di, ob-la-da', 193);
insert into tracks(albumid, title, duration) values (3, 'Dear Prudence', 231);
insert into tracks(albumid, title, duration) values (3, 'Im so tired (another mix)', 124);
insert into tracks(albumid, title, duration) values (3, 'Ob-la-di, ob-la-da (another mix)', 189);
insert into tracks(albumid, title, duration) values (3, 'Sexy Sadie (different version)', 142);
insert into tracks(albumid, title, duration) values (3, 'Brian Epstein blues', 61);
insert into PerformersAlbums(performerID, albumID) values (2, 3) ON CONFLICT DO NOTHING;

insert into albums(title, year) values ('A Hard Day&amps Night', 1964);
insert into gengres(name) values ('Classic Rock');
insert into PerformersGengres(GengreID, performerID) values (3, 2) ON CONFLICT DO NOTHING;
insert into tracks(albumid, title, duration) values (4, 'A Hard Day&amps Night', 154);
insert into tracks(albumid, title, duration) values (4, 'I Should Have Known Better', 166);
insert into tracks(albumid, title, duration) values (4, 'If I Fell', 145);
insert into tracks(albumid, title, duration) values (4, 'I&ampm Happy Just to Dance With You', 121);
insert into tracks(albumid, title, duration) values (4, 'And I Love Her', 154);
insert into tracks(albumid, title, duration) values (4, 'Tell Me Why', 133);
insert into tracks(albumid, title, duration) values (4, 'Can&ampt Buy Me Love', 136);
insert into tracks(albumid, title, duration) values (4, 'Any Time at All', 136);
insert into tracks(albumid, title, duration) values (4, 'I&ampll Cry Instead', 109);
insert into tracks(albumid, title, duration) values (4, 'Things We Said Today', 160);
insert into tracks(albumid, title, duration) values (4, 'When I Get Home', 141);
insert into tracks(albumid, title, duration) values (4, 'You Can&ampt Do That', 160);
insert into tracks(albumid, title, duration) values (4, 'I&ampll Be Back', 139);
insert into PerformersAlbums(performerID, albumID) values (2, 4) ON CONFLICT DO NOTHING;

insert into performers(name) values ('Bob Marley & The Wailers');
insert into albums(title, year) values ('Exodus', 1977);
insert into gengres(name) values ('Reggae');
insert into PerformersGengres(GengreID, performerID) values (4, 3) ON CONFLICT DO NOTHING;
insert into tracks(albumid, title, duration) values (5, 'Natural Mystic', 208);
insert into tracks(albumid, title, duration) values (5, 'So Much Things To Say', 187);
insert into tracks(albumid, title, duration) values (5, 'Guiltiness', 199);
insert into tracks(albumid, title, duration) values (5, 'The Heathen', 153);
insert into tracks(albumid, title, duration) values (5, 'Exodus', 454);
insert into tracks(albumid, title, duration) values (5, 'Jamming', 211);
insert into tracks(albumid, title, duration) values (5, 'Waiting In Vain', 256);
insert into tracks(albumid, title, duration) values (5, 'Turn Your Lights Down Low', 220);
insert into tracks(albumid, title, duration) values (5, 'Three Little Birds', 181);
insert into tracks(albumid, title, duration) values (5, 'One Love-People Get Ready', 169);
insert into PerformersAlbums(performerID, albumID) values (3, 5) ON CONFLICT DO NOTHING;

insert into performers(name) values ('Nirvana');
insert into albums(title, year) values ('Bleach', 1989);
insert into gengres(name) values ('Alternative');
insert into PerformersGengres(GengreID, performerID) values (5, 4) ON CONFLICT DO NOTHING;
insert into tracks(albumid, title, duration) values (6, 'Blew', 208);
insert into tracks(albumid, title, duration) values (6, 'Floyd The Barber', 208);
insert into tracks(albumid, title, duration) values (6, 'About A Girl', 208);
insert into tracks(albumid, title, duration) values (6, 'School', 208);
insert into tracks(albumid, title, duration) values (6, 'Love Buzz', 208);
insert into tracks(albumid, title, duration) values (6, 'Paper Cuts', 208);
insert into tracks(albumid, title, duration) values (6, 'Negative Creep', 208);
insert into tracks(albumid, title, duration) values (6, 'Scoff', 208);
insert into tracks(albumid, title, duration) values (6, 'Swap Meet', 208);
insert into tracks(albumid, title, duration) values (6, 'Mr. Moustache', 208);
insert into tracks(albumid, title, duration) values (6, 'Sifting', 208);
insert into tracks(albumid, title, duration) values (6, 'Big Cheese', 208);
insert into tracks(albumid, title, duration) values (6, 'Downer', 208);
insert into PerformersAlbums(performerID, albumID) values (4, 6) ON CONFLICT DO NOTHING;

insert into albums(title, year) values ('COMA', 1994);
insert into gengres(name) values ('Grunge');
insert into PerformersGengres(GengreID, performerID) values (6, 4) ON CONFLICT DO NOTHING;
insert into tracks(albumid, title, duration) values (7, 'RADIO FRIENDLY UNIT SHIFTER', 271);
insert into tracks(albumid, title, duration) values (7, 'DRAIN YOU', 216);
insert into tracks(albumid, title, duration) values (7, 'BREED', 283);
insert into tracks(albumid, title, duration) values (7, 'SERVE THE SERVANTS', 141);
insert into tracks(albumid, title, duration) values (7, 'COME AS YOU ARE', 225);
insert into tracks(albumid, title, duration) values (7, 'SMELLS LIKE TEEN SPITIT', 295);
insert into tracks(albumid, title, duration) values (7, 'SLIVER', 115);
insert into tracks(albumid, title, duration) values (7, 'DUMB', 162);
insert into tracks(albumid, title, duration) values (7, 'IN BLOOM', 297);
insert into tracks(albumid, title, duration) values (7, 'ABOUT A GIRL', 177);
insert into tracks(albumid, title, duration) values (7, 'LITHIUM', 249);
insert into tracks(albumid, title, duration) values (7, 'PENNYROYAL TEA', 220);
insert into tracks(albumid, title, duration) values (7, 'SCHOOL', 166);
insert into tracks(albumid, title, duration) values (7, 'POLLY', 181);
insert into tracks(albumid, title, duration) values (7, 'VERY APE', 33);
insert into tracks(albumid, title, duration) values (7, 'LOUNGE ACT', 303);
insert into tracks(albumid, title, duration) values (7, 'RAPE ME', 175);
insert into tracks(albumid, title, duration) values (7, 'TERRITORIAL PISSINGS', 163);
insert into tracks(albumid, title, duration) values (7, 'ALL APOLOGIES', 205);
insert into tracks(albumid, title, duration) values (7, 'ON A PLAIN', 213);
insert into tracks(albumid, title, duration) values (7, 'SCENTLESS APPRENTICE', 213);
insert into tracks(albumid, title, duration) values (7, 'HEART-SHAPED BOX', 190);
insert into PerformersAlbums(performerID, albumID) values (4, 7) ON CONFLICT DO NOTHING;

insert into performers(name) values ('Spice Girls');
insert into albums(title, year) values ('Forever', 2000);
insert into PerformersGengres(GengreID, performerID) values (2, 5) ON CONFLICT DO NOTHING;
insert into tracks(albumid, title, duration) values (8, 'Holler', 256);
insert into tracks(albumid, title, duration) values (8, 'Tell Me Why', 255);
insert into tracks(albumid, title, duration) values (8, 'Let Love Lead The Way', 298);
insert into tracks(albumid, title, duration) values (8, 'Right Back At Ya', 250);
insert into tracks(albumid, title, duration) values (8, 'Get Down With Me', 226);
insert into tracks(albumid, title, duration) values (8, 'Wasting My Time', 255);
insert into tracks(albumid, title, duration) values (8, 'Weekend Love', 247);
insert into tracks(albumid, title, duration) values (8, 'Time Goes By', 292);
insert into tracks(albumid, title, duration) values (8, 'If You Wanna Have Some Fun', 327);
insert into tracks(albumid, title, duration) values (8, 'Oxygen', 298);
insert into tracks(albumid, title, duration) values (8, 'Goodbye', 274);
insert into PerformersAlbums(performerID, albumID) values (5, 8) ON CONFLICT DO NOTHING;

insert into performers(name) values ('Ariana Grande');
insert into albums(title, year) values ('Thank U, Next', 2019);
insert into PerformersGengres(GengreID, performerID) values (2, 6) ON CONFLICT DO NOTHING;
insert into tracks(albumid, title, duration) values (9, 'Imagine', 213);
insert into tracks(albumid, title, duration) values (9, 'Needy', 172);
insert into tracks(albumid, title, duration) values (9, 'NASA', 181);
insert into tracks(albumid, title, duration) values (9, 'Bloodline', 217);
insert into tracks(albumid, title, duration) values (9, 'Fake Smile', 208);
insert into tracks(albumid, title, duration) values (9, 'Bad Idea', 268);
insert into tracks(albumid, title, duration) values (9, 'Make Up', 141);
insert into tracks(albumid, title, duration) values (9, 'Ghostin', 271);
insert into tracks(albumid, title, duration) values (9, 'In My Head', 223);
insert into tracks(albumid, title, duration) values (9, '7 Rings', 178);
insert into tracks(albumid, title, duration) values (9, 'Thank U, Next', 208);
insert into tracks(albumid, title, duration) values (9, 'Break Up With Your Girlfriend, I&ampm Bored', 189);
insert into PerformersAlbums(performerID, albumID) values (6, 9) ON CONFLICT DO NOTHING;

insert into albums(title, year) values ('Sweetener', 2018);
insert into PerformersGengres(GengreID, performerID) values (2, 6) ON CONFLICT DO NOTHING;
insert into tracks(albumid, title, duration) values (10, 'Raindrops (An Angel Cried)', 37);
insert into tracks(albumid, title, duration) values (10, 'Blazed ft. Pharrell Williams', 196);
insert into tracks(albumid, title, duration) values (10, 'The Light Is Coming ft. Nicki Minaj', 229);
insert into tracks(albumid, title, duration) values (10, 'R.E.M', 245);
insert into tracks(albumid, title, duration) values (10, 'God Is A Woman', 198);
insert into tracks(albumid, title, duration) values (10, 'Sweetener', 208);
insert into tracks(albumid, title, duration) values (10, 'Successful', 228);
insert into tracks(albumid, title, duration) values (10, 'Everytime', 172);
insert into tracks(albumid, title, duration) values (10, 'Breathin', 199);
insert into tracks(albumid, title, duration) values (10, 'No Tears Left To Cry', 205);
insert into tracks(albumid, title, duration) values (10, 'Borderline ft. Missy Elliott', 178);
insert into tracks(albumid, title, duration) values (10, 'Better Off', 172);
insert into tracks(albumid, title, duration) values (10, 'Goodnight &ampn&amp Go (Imogen Heap cover)', 190);
insert into tracks(albumid, title, duration) values (10, 'Pete Davidson', 73);
insert into tracks(albumid, title, duration) values (10, 'Get Well Soon', 319);
insert into PerformersAlbums(performerID, albumID) values (6, 10) ON CONFLICT DO NOTHING;

insert into performers(name) values ('Katy Perry');
insert into albums(title, year) values ('One of the Boys', 2008);
insert into PerformersGengres(GengreID, performerID) values (2, 7) ON CONFLICT DO NOTHING;
insert into tracks(albumid, title, duration) values (11, 'One Of The Boys', 250);
insert into tracks(albumid, title, duration) values (11, 'I Kissed A Girl', 183);
insert into tracks(albumid, title, duration) values (11, 'Waking Up In Vegas', 202);
insert into tracks(albumid, title, duration) values (11, 'Thinking Of You', 249);
insert into tracks(albumid, title, duration) values (11, 'Mannequin', 199);
insert into tracks(albumid, title, duration) values (11, 'Ur So Gay', 220);
insert into tracks(albumid, title, duration) values (11, 'Hot N Cold', 223);
insert into tracks(albumid, title, duration) values (11, 'If You Can Afford Me', 201);
insert into tracks(albumid, title, duration) values (11, 'Lost', 258);
insert into tracks(albumid, title, duration) values (11, 'Self Inflicted', 208);
insert into tracks(albumid, title, duration) values (11, 'I&ampm Still Breathing', 231);
insert into tracks(albumid, title, duration) values (11, 'Fingerprints', 223);
insert into PerformersAlbums(performerID, albumID) values (7, 11) ON CONFLICT DO NOTHING;

insert into performers(name) values ('Limp Bizkit');
insert into albums(title, year) values ('Behind Blue Eyes', 2005);
insert into gengres(name) values ('New Age');
insert into PerformersGengres(GengreID, performerID) values (7, 8) ON CONFLICT DO NOTHING;
insert into tracks(albumid, title, duration) values (12, 'Behind Blue Eyes', 273);
insert into tracks(albumid, title, duration) values (12, 'Just Drop Dead', 244);
insert into tracks(albumid, title, duration) values (12, 'My Way (remixed by DJ Lethal)', 271);
insert into tracks(albumid, title, duration) values (12, 'Re-Entry', 160);
insert into tracks(albumid, title, duration) values (12, 'Eat You Alive', 240);
insert into tracks(albumid, title, duration) values (12, 'Gimme The Mic', 187);
insert into tracks(albumid, title, duration) values (12, 'Underneath The Gun', 345);
insert into tracks(albumid, title, duration) values (12, 'Down Another Day', 249);
insert into tracks(albumid, title, duration) values (12, 'Almost Over', 280);
insert into tracks(albumid, title, duration) values (12, 'Build A Bridge', 238);
insert into tracks(albumid, title, duration) values (12, 'Red Light-Green Light', 339);
insert into tracks(albumid, title, duration) values (12, 'The Only One', 245);
insert into PerformersAlbums(performerID, albumID) values (8, 12) ON CONFLICT DO NOTHING;

insert into collections(title, year) values ('Collection 1', 2017);
insert into CollectionsTracks(CollectionID, TrackID) values (1, 130) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (1, 76) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (1, 50) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (1, 73) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (1, 104) ON CONFLICT DO NOTHING;
insert into collections(title, year) values ('Collection 2', 2018);
insert into CollectionsTracks(CollectionID, TrackID) values (2, 24) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (2, 41) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (2, 122) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (2, 54) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (2, 97) ON CONFLICT DO NOTHING;
insert into collections(title, year) values ('Collection 3', 2020);
insert into CollectionsTracks(CollectionID, TrackID) values (3, 127) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (3, 77) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (3, 96) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (3, 104) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (3, 87) ON CONFLICT DO NOTHING;
insert into collections(title, year) values ('Collection 4', 2016);
insert into CollectionsTracks(CollectionID, TrackID) values (4, 30) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (4, 91) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (4, 8) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (4, 13) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (4, 77) ON CONFLICT DO NOTHING;
insert into collections(title, year) values ('Collection 5', 2018);
insert into CollectionsTracks(CollectionID, TrackID) values (5, 29) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (5, 8) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (5, 75) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (5, 149) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (5, 81) ON CONFLICT DO NOTHING;
insert into collections(title, year) values ('Collection 6', 2017);
insert into CollectionsTracks(CollectionID, TrackID) values (6, 67) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (6, 54) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (6, 98) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (6, 90) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (6, 130) ON CONFLICT DO NOTHING;
insert into collections(title, year) values ('Collection 7', 2017);
insert into CollectionsTracks(CollectionID, TrackID) values (7, 102) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (7, 143) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (7, 168) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (7, 31) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (7, 83) ON CONFLICT DO NOTHING;
insert into collections(title, year) values ('Collection 8', 2019);
insert into CollectionsTracks(CollectionID, TrackID) values (8, 82) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (8, 46) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (8, 122) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (8, 31) ON CONFLICT DO NOTHING;
insert into CollectionsTracks(CollectionID, TrackID) values (8, 160) ON CONFLICT DO NOTHING;
